spring:
  application:
    name: comment

  cloud:
    config:
      uri: http://localhost:8888  # URL for Spring Cloud Config Server

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_comment
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8083












#spring.datasource.url: jdbc:mysql://localhost:3306/microservice_comment
#spring.datasource.password: test
#spring.datasource.username: root
#
#spring.jpa.hibernate.ddl-auto: update
#spring.jpa.show-sql: true
#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#
#server.port: 8083

